apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathnex-grafana
  labels:
    app: pathnex-grafana
spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      app: pathnex-grafana

  template:
    metadata:
      labels:
        app: pathnex-grafana

    spec:
      securityContext:
        fsGroup: 472

      containers:
        - name: pathnex-grafana
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          ports:
            - containerPort: {{ .Values.service.targetPort }}

          env:
            - name: GF_SECURITY_ADMIN_USER
              value: "{{ .Values.adminUser }}"

            - name: GF_SECURITY_ADMIN_PASSWORD
              value: "{{ .Values.adminPassword }}"

          volumeMounts:
            - name: grafana-storage
              mountPath: /var/lib/grafana

      volumes:
        - name: grafana-storage
          persistentVolumeClaim:
            claimName: pathnex-grafana-pvc
