apiVersion: apps/v1
kind: Deployment
metadata:
  name: pathnex-nginx
  labels:
    app: pathnex-nginx
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: pathnex-nginx
  template:
    metadata:
      labels:
        app: pathnex-nginx
    spec:
      containers:
        - name: pathnex-nginx
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}