apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  labels:
    app: pathnex-nginx
spec:
  type: {{ .Values.service.type }}
  selector:
    app: pathnex-nginx
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}