replicaCount: 1

image:
  repository: grafana/grafana
  tag: 10.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  name: grafana-service
  port: 80
  targetPort: 3000

persistence:
  enabled: true
  size: 10Gi
  storageClass: local-path
